cores: picorv32-wb-soc: fix iverilog simulation
$ iverilog -V | head -n1
Icarus Verilog version 12.0 (stable) ()
$ fusesoc --cores-root cores/ run --target sim picorv32-wb-soc
...
iverilog -spicorv32_wb_soc_tb -c picorv32-wb-soc_0.scr -o
picorv32-wb-soc_0 -DPRESCALER_PRESET_HARD -DPRESCALER_HIGH_PRESET=0
-DPRESCALER_LOW_PRESET=2 -DSIM
../src/picorv32-wb-soc_0/bench/picorv32_wb_soc_tb.v:15: error:
'wb_clk_o' has already been declared in this scope.
../src/picorv32-wb-soc_0/bench/picorv32_wb_soc_tb.v:4:      : It was
declared here as a net.
../src/picorv32-wb-soc_0/bench/picorv32_wb_soc_tb.v:22: error:
'sdram_clk_o' has already been declared in this scope.
../src/picorv32-wb-soc_0/bench/picorv32_wb_soc_tb.v:7:      : It was
declared here as a net.
make: *** [Makefile:9: picorv32-wb-soc_0] Error 2
ERROR: Failed to build ::picorv32-wb-soc:0 : '['make']' exited with an
error: 2

Signed-off-by: Antony Pavlov <antonynpavlov@gmail.com>